# Generated by Django 5.0.8 on 2024-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=23)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=23)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
